# Generated by Django 4.2.19 on 2025-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_type',
            field=models.CharField(choices=[('TV', 'Сериал'), ('Movie', 'Фильм')], default='TV', max_length=10),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
